### ISSUE TITLE
Donations per minute chart wrong

### ISSUE THREAD

**Issue by Ladish** [bcongdon/gdq-stats#18]
When the data is missing for a period of time, the stats combine all donations during the time span into the last minute, making a unrealistic bump in the donations per minute chart. It happened between 2:01 to 4:20 PM EST today (http://gdqstat.us/?series=2).

**Comment by bcongdon** [comment]
Thanks for the report. I believe this is fixed now, as of babedb5a67785f9fc83527039eeb46a3c11d2fca
